// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_Petshop.Data;

namespace WebAPI_Petshop.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WebAPI_Petshop.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAccommodation")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeAccommodation = "Acomodação 1",
                            PetId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            NomeAccommodation = "Acomodação 2",
                            PetId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            NomeAccommodation = "Acomodação 3",
                            PetId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            NomeAccommodation = "Acomodação 4",
                            PetId = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            NomeAccommodation = "Acomodação 5",
                            PetId = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            NomeAccommodation = "Acomodação 6",
                            PetId = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            NomeAccommodation = "Acomodação 7",
                            PetId = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            NomeAccommodation = "Acomodação 8",
                            PetId = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            NomeAccommodation = "Acomodação 9",
                            PetId = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            NomeAccommodation = "Acomodação 10",
                            PetId = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("WebAPI_Petshop.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccommodationPetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cause")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeaulthStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccommodationPetId = 3,
                            Cause = "Febre canina",
                            HeaulthStatus = 0,
                            Name = "Bethoven",
                            OwnerAddress = "Av. dos Pets, 1234",
                            OwnerName = "Antônio Vasconcelos",
                            OwnerPhone = "85912345678"
                        },
                        new
                        {
                            Id = 2,
                            AccommodationPetId = 1,
                            Cause = "Incômodo na coluna vertebral",
                            HeaulthStatus = 0,
                            Name = "Yoda",
                            OwnerAddress = "Av. dos Jedi, s/n",
                            OwnerName = "Anakim",
                            OwnerPhone = "85901101010"
                        },
                        new
                        {
                            Id = 3,
                            AccommodationPetId = 2,
                            Cause = "Perda de visão no olho",
                            HeaulthStatus = 0,
                            Name = "Dalek",
                            OwnerAddress = "Av. Tardis, 987",
                            OwnerName = "Dora Holanda",
                            OwnerPhone = "85543215678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
